version: "3.8"

services:
  bot:
    build: .
    restart: always
    ports:
      - "8080:8080"
    env_file:
      bot.env
    links:
      - "db:db"

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - sobaka-data:/var/lib/postgresql/data

volumes:
  sobaka-data:
