version: "3.8"

services:
  bot:
    build: .
    restart: always
    ports:
      - "8080:8080"
    env_file:
      bot.env
    links:
      - "db:db"
    depends_on:
          - db
          - cache

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - sobaka-data:/var/lib/postgresql/data

  cache:
    image: "redis"
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
volumes:
  sobaka-data:
